version: "3.9"

services:

  web:

    build:
      context: .

    container_name: weather_backend

    command: python manage.py runserver 0.0.0.0:8000

    working_dir: /app/src/weather

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

  postgres:

    image: postgres:17

    container_name: weather_postgres

    restart: always

    environment:

      POSTGRES_DB: ${DB_NAME}

      POSTGRES_USER: ${DB_USER}

      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

  redis:

    image: redis:7-alpine

    container_name: weather_redis

    restart: always

    ports:
      - "6379:6379"

  celery:

    build:
      context: .

    container_name: weather_celery

    working_dir: /app/src/weather

    command: celery -A weather worker --loglevel=info

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - redis
      - postgres

  celery-beat:

    build:
      context: .

    container_name: weather_celery_beat

    working_dir: /app/src/weather

    command: celery -A weather beat --loglevel=info

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - redis
      - postgres

  flower:

    build:
      context: .

    container_name: weather_flower

    command: >
      celery -A weather flower
      --port=5555

    working_dir: /app/src/weather

    volumes:
      - .:/app

    env_file:
      - .env

    ports:
      - "5555:5555"

    depends_on:
      - redis
      - celery

volumes:

  postgres_data:

