# Generated by Django 6.0.6 on 2026-07-08 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('weatherapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('wind_speed', 'Wind Speed'), ('pressure', 'Pressure'), ('uv_index', 'UV Index'), ('condition', 'Weather Condition')], db_index=True, max_length=30)),
                ('operator', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than Equal'), ('lt', 'Less Than'), ('lte', 'Less Than Equal'), ('eq', 'Equal')], max_length=5)),
                ('threshold', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='cities.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weather_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('weather_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='weatherapp.weatherrecord')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.weatheralert')),
            ],
            options={
                'db_table': 'alert_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['user', 'city'], name='weather_ale_user_id_d0f84a_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['alert_type', 'is_active'], name='weather_ale_alert_t_e8a0e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='weatheralert',
            constraint=models.UniqueConstraint(fields=('user', 'city', 'alert_type', 'operator', 'threshold'), name='unique_weather_alert'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['is_read', 'created_at'], name='alert_notif_is_read_8de0c8_idx'),
        ),
    ]
