# Generated by Django 6.0.6 on 2026-07-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatheralert',
            name='is_triggered',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
