# Generated by Django 6.0.6 on 2026-06-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feels_like', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_direction', models.IntegerField(blank=True, null=True)),
                ('visibility', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('uv_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weather', models.CharField(blank=True, max_length=100, null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_weather', to='cities.city')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['recorded_at'], name='weatherapp__recorde_02acab_idx')],
            },
        ),
    ]
